#!/usr/bin/env bash
# PostCompact hook — captures compact_summary to .claude/session/last-compact.md
# Fires after Claude Code compacts the context window (auto or manual).
#
# Enhancements (v3.6.3):
#  - Filter compact_summary through scripts/compact-filter.py before persisting.
#    Conservative cleanup: collapses oversize fenced blocks, dense unprotected
#    runs, and triplicate paragraphs. Never drops headings, paths, or
#    decision/error/fix lines. Worst case: file unchanged.
#  - Keep a rotating history under .claude/session/compact-history/
#    (last 5 checkpoints, named by ISO timestamp). Lets you diff between
#    compactions or recover from a stale last-compact.md.
#  - Filter is best-effort: if scripts/compact-filter.py is missing or fails,
#    fall back to writing the raw summary so we never lose context.

set -uo pipefail

HOOK_INPUT=$(cat)
TRIGGER=$(echo "$HOOK_INPUT" | python3 -c "import json,sys; d=json.load(sys.stdin); print(d.get('trigger','auto'))" 2>/dev/null || echo "auto")
RAW_SUMMARY=$(echo "$HOOK_INPUT" | python3 -c "import json,sys; d=json.load(sys.stdin); print(d.get('compact_summary',''))" 2>/dev/null || echo "")

SESSION_DIR=".claude/session"
HISTORY_DIR="$SESSION_DIR/compact-history"
CHECKPOINT_FILE="$SESSION_DIR/last-compact.md"
FILTER_SCRIPT="scripts/compact-filter.py"

mkdir -p "$SESSION_DIR" "$HISTORY_DIR"

TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
ISO_FILE_TS=$(date -u +"%Y%m%dT%H%M%SZ")
GIT_STATUS=$(git status --short 2>/dev/null | head -20 || echo "not a git repo")
GIT_BRANCH=$(git branch --show-current 2>/dev/null || echo "unknown")

# Run summary through compact-filter if available; fall back to raw on any error
FILTER_METRICS=""
if [ -n "$RAW_SUMMARY" ] && [ -x "$FILTER_SCRIPT" ]; then
    FILTER_TMP=$(mktemp)
    FILTER_ERR=$(mktemp)
    if printf '%s' "$RAW_SUMMARY" | "$FILTER_SCRIPT" >"$FILTER_TMP" 2>"$FILTER_ERR"; then
        SUMMARY=$(cat "$FILTER_TMP")
        FILTER_METRICS=$(cat "$FILTER_ERR")
    else
        SUMMARY="$RAW_SUMMARY"
        FILTER_METRICS="[compact-filter] failed; using raw summary"
    fi
    rm -f "$FILTER_TMP" "$FILTER_ERR"
else
    SUMMARY="$RAW_SUMMARY"
    FILTER_METRICS="[compact-filter] not run (script missing or empty summary)"
fi

write_checkpoint() {
    local target="$1"
    cat > "$target" <<EOF
# Context Checkpoint
**Compacted:** $TIMESTAMP
**Trigger:** $TRIGGER
**Branch:** $GIT_BRANCH
**Filter:** ${FILTER_METRICS:-n/a}

## Summary (generated by Claude Code, filtered by compact-filter)

$SUMMARY

## Working Tree at Compaction

\`\`\`
$GIT_STATUS
\`\`\`
EOF
}

write_checkpoint "$CHECKPOINT_FILE"
write_checkpoint "$HISTORY_DIR/${ISO_FILE_TS}.md"

# Rotate history: keep last 5 only
ls -1t "$HISTORY_DIR"/*.md 2>/dev/null | tail -n +6 | xargs -I {} rm -f {} 2>/dev/null || true

echo "[post-compact] Checkpoint saved to $CHECKPOINT_FILE" >&2
echo "[post-compact] History entry: $HISTORY_DIR/${ISO_FILE_TS}.md" >&2
[ -n "$FILTER_METRICS" ] && echo "$FILTER_METRICS" >&2
exit 0
