#!/usr/bin/env bash
# Config Self-Validation Test Suite
# Validates internal coherence of a Claude Code configuration generated by dotforge.
# Usage: bash tests/test-config.sh [project-dir]
# Exit 0 = all pass, exit 1 = failures found

set -euo pipefail

PROJECT_DIR="${1:-.}"
PASS=0
FAIL=0
WARN=0

# Colors (disable if not a terminal)
if [[ -t 1 ]]; then
  GREEN='\033[0;32m'; RED='\033[0;31m'; YELLOW='\033[0;33m'; NC='\033[0m'
else
  GREEN=''; RED=''; YELLOW=''; NC=''
fi

pass() { ((PASS++)); echo -e "  ${GREEN}✓${NC} $1"; }
fail() { ((FAIL++)); echo -e "  ${RED}✗${NC} $1"; }
warn() { ((WARN++)); echo -e "  ${YELLOW}⚠${NC} $1"; }

echo "═══ Config Validation: $(basename "$PROJECT_DIR") ═══"
echo ""

# ── 1. CLAUDE.md ──
echo "── CLAUDE.md ──"
CLAUDE_MD="$PROJECT_DIR/CLAUDE.md"
if [[ -f "$CLAUDE_MD" ]]; then
  pass "CLAUDE.md exists"

  LINE_COUNT=$(grep -c '.' "$CLAUDE_MD" 2>/dev/null || echo "0")
  if [[ "$LINE_COUNT" -ge 20 ]]; then
    pass "CLAUDE.md has $LINE_COUNT lines (≥20)"
  else
    fail "CLAUDE.md has only $LINE_COUNT lines (<20)"
  fi

  # Check required sections (case-insensitive, flexible matching)
  SECTIONS_FOUND=0
  SECTIONS_CHECKED=0
  for section_pair in \
    "stack|tecnolog|technology|what is|framework|lang|python|react|swift|typescript|fastapi|vite:stack/technology" \
    "build|test|command|comando|validation|dev|run:build/test commands" \
    "architect|estructura|structure|module|component|layer|capa|pipeline|services|service|flujo|flow:architecture/structure"; do
    ((SECTIONS_CHECKED++))
    PATTERN="${section_pair%%:*}"
    LABEL="${section_pair##*:}"
    if grep -qiE "$PATTERN" "$CLAUDE_MD" 2>/dev/null; then
      pass "CLAUDE.md contains: $LABEL"
      ((SECTIONS_FOUND++))
    else
      fail "CLAUDE.md missing: $LABEL"
    fi
  done
else
  fail "CLAUDE.md does not exist"
fi
echo ""

# ── 2. settings.json ──
echo "── settings.json ──"
SETTINGS="$PROJECT_DIR/.claude/settings.json"
if [[ -f "$SETTINGS" ]]; then
  pass "settings.json exists"

  # Valid JSON
  if jq empty "$SETTINGS" 2>/dev/null; then
    pass "settings.json is valid JSON"
  else
    fail "settings.json is NOT valid JSON"
  fi

  # Deny list exists
  DENY_COUNT=$(jq -r '.permissions.deny // [] | length' "$SETTINGS" 2>/dev/null || echo "0")
  if [[ "$DENY_COUNT" -gt 0 ]]; then
    pass "deny list has $DENY_COUNT entries"
  else
    fail "deny list is empty or missing"
  fi

  # Minimum deny patterns
  DENY_LIST=$(jq -r '.permissions.deny[]? // empty' "$SETTINGS" 2>/dev/null || echo "")
  for pattern in ".env" "*.key" "*.pem"; do
    if echo "$DENY_LIST" | grep -q "$pattern"; then
      pass "deny list covers $pattern"
    else
      fail "deny list missing $pattern"
    fi
  done

  # Hooks section exists
  if jq -e '.hooks' "$SETTINGS" >/dev/null 2>&1; then
    pass "hooks section exists in settings.json"
  else
    warn "no hooks section in settings.json"
  fi

  # Verify hook references point to existing files
  HOOK_COMMANDS=$(jq -r '.. | .command? // empty' "$SETTINGS" 2>/dev/null | grep -v '^$' || true)
  if [[ -n "$HOOK_COMMANDS" ]]; then
    while IFS= read -r hook_cmd; do
      # Resolve relative to project dir
      HOOK_PATH="$PROJECT_DIR/$hook_cmd"
      if [[ -f "$HOOK_PATH" ]]; then
        pass "hook exists: $hook_cmd"
        if [[ -x "$HOOK_PATH" ]]; then
          pass "hook is executable: $hook_cmd"
        else
          fail "hook is NOT executable: $hook_cmd (run: chmod +x $hook_cmd)"
        fi
      else
        fail "hook referenced but missing: $hook_cmd"
      fi
    done <<< "$HOOK_COMMANDS"
  fi

  # Check for contradictory allow+deny patterns
  ALLOW_LIST=$(jq -r '.permissions.allow[]? // empty' "$SETTINGS" 2>/dev/null || echo "")
  while IFS= read -r deny_pattern; do
    [[ -z "$deny_pattern" ]] && continue
    # Extract the core pattern (e.g., "Read(.env)" → ".env")
    CORE=$(echo "$deny_pattern" | sed 's/^[^(]*(\(.*\))$/\1/' 2>/dev/null)
    if echo "$ALLOW_LIST" | grep -qF "$CORE" 2>/dev/null; then
      fail "contradictory: '$CORE' appears in both allow and deny"
    fi
  done <<< "$DENY_LIST"

else
  fail "settings.json does not exist"
fi
echo ""

# ── 3. Rules ──
echo "── Rules ──"
RULES_DIR="$PROJECT_DIR/.claude/rules"
if [[ -d "$RULES_DIR" ]]; then
  RULE_FILES=$(find "$RULES_DIR" -name "*.md" -type f 2>/dev/null)
  RULE_COUNT=$(echo "$RULE_FILES" | grep -c '.' 2>/dev/null || echo "0")

  if [[ "$RULE_COUNT" -gt 0 ]]; then
    pass "$RULE_COUNT rule file(s) found"
  else
    fail "rules directory exists but is empty"
  fi

  # Check frontmatter globs
  while IFS= read -r rule_file; do
    [[ -z "$rule_file" ]] && continue
    BASENAME=$(basename "$rule_file")

    # Check for globs: in frontmatter (between --- markers)
    if head -5 "$rule_file" | grep -q 'globs:'; then
      GLOB_VALUE=$(head -5 "$rule_file" | grep 'globs:' | sed 's/globs: *"\{0,1\}//' | sed 's/"\{0,1\} *$//')

      if [[ -n "$GLOB_VALUE" && "$GLOB_VALUE" != '""' ]]; then
        pass "$BASENAME has globs: $GLOB_VALUE"

        # Check if glob matches at least 1 real file (skip **/* which always matches)
        if [[ "$GLOB_VALUE" != "**/*" ]]; then
          # Split comma-separated globs and test each
          MATCHED=false
          IFS=',' read -ra GLOBS <<< "$GLOB_VALUE"
          for g in "${GLOBS[@]}"; do
            g=$(echo "$g" | xargs) # trim whitespace
            if compgen -G "$PROJECT_DIR/$g" >/dev/null 2>&1; then
              MATCHED=true
              break
            fi
          done
          if $MATCHED; then
            pass "$BASENAME glob matches real files"
          else
            warn "$BASENAME glob matches NO files in project (may be stale)"
          fi
        fi
      else
        warn "$BASENAME has empty globs value"
      fi
    else
      warn "$BASENAME has no globs: frontmatter (always loads)"
    fi
  done <<< "$RULE_FILES"
else
  fail ".claude/rules/ directory does not exist"
fi
echo ""

# ── 4. CLAUDE_ERRORS.md ──
echo "── CLAUDE_ERRORS.md ──"
ERRORS_FILE="$PROJECT_DIR/CLAUDE_ERRORS.md"
if [[ -f "$ERRORS_FILE" ]]; then
  pass "CLAUDE_ERRORS.md exists"
  if grep -qE '^\|.*\|.*\|' "$ERRORS_FILE" 2>/dev/null; then
    pass "CLAUDE_ERRORS.md has table format"
  elif grep -qE '^### ' "$ERRORS_FILE" 2>/dev/null; then
    pass "CLAUDE_ERRORS.md has structured entries"
  else
    warn "CLAUDE_ERRORS.md exists but may lack structured format"
  fi
else
  warn "CLAUDE_ERRORS.md does not exist (recommended for error tracking)"
fi
echo ""

# ── 5. .gitignore secrets ──
echo "── .gitignore ──"
GITIGNORE="$PROJECT_DIR/.gitignore"
if [[ -f "$GITIGNORE" ]]; then
  pass ".gitignore exists"
  for pattern in ".env" "*.key" "*.pem"; do
    if grep -q "$pattern" "$GITIGNORE" 2>/dev/null; then
      pass ".gitignore covers $pattern"
    else
      warn ".gitignore missing $pattern"
    fi
  done
else
  warn ".gitignore does not exist"
fi
echo ""

# ── 6. Prompt injection scan ──
# Scan only shipped/synced config — NOT worktrees, agent-memory (local), benchmark
# fixtures, or doc examples that legitimately quote injection patterns as
# illustrations. Exclusions are below.
echo "── Prompt injection scan ──"
SUSPICIOUS_PATTERNS='ignore previous|IGNORE ALL|disregard|override instructions|<system>|</system>|<instructions>.*</instructions>'
SCAN_FILES=$(find "$PROJECT_DIR/.claude" "$PROJECT_DIR/CLAUDE.md" -name "*.md" -type f 2>/dev/null \
  | grep -vE '/\.claude/worktrees/|/\.claude/agent-memory/|/\.claude/sessions/|/tests/benchmark-tasks/|/tests/fixtures/' \
  || true)
INJECTION_FOUND=false
while IFS= read -r scan_file; do
  [[ -z "$scan_file" ]] && continue
  if grep -qiE "$SUSPICIOUS_PATTERNS" "$scan_file" 2>/dev/null; then
    fail "suspicious pattern in: $(basename "$scan_file")"
    INJECTION_FOUND=true
  fi
done <<< "$SCAN_FILES"
if ! $INJECTION_FOUND; then
  pass "no suspicious prompt injection patterns found"
fi
echo ""

# ── Summary ──
TOTAL=$((PASS + FAIL + WARN))
echo "═══ RESULTS ═══"
echo -e "  ${GREEN}$PASS passed${NC}  ${RED}$FAIL failed${NC}  ${YELLOW}$WARN warnings${NC}  ($TOTAL checks)"
echo ""

if [[ "$FAIL" -gt 0 ]]; then
  echo "STATUS: FAIL — fix $FAIL issue(s) before deploying"
  exit 1
else
  if [[ "$WARN" -gt 0 ]]; then
    echo "STATUS: PASS with $WARN warning(s)"
  else
    echo "STATUS: PASS — config is internally coherent"
  fi
  exit 0
fi
