#!/usr/bin/env bash
# PostCompact hook — captures compact_summary to .claude/session/last-compact.md
# Fires after Claude Code compacts the context window (auto or manual)

set -euo pipefail

HOOK_INPUT=$(cat)
TRIGGER=$(echo "$HOOK_INPUT" | python3 -c "import json,sys; d=json.load(sys.stdin); print(d.get('trigger','auto'))" 2>/dev/null || echo "auto")
SUMMARY=$(echo "$HOOK_INPUT" | python3 -c "import json,sys; d=json.load(sys.stdin); print(d.get('compact_summary',''))" 2>/dev/null || echo "")

SESSION_DIR=".claude/session"
CHECKPOINT_FILE="$SESSION_DIR/last-compact.md"

mkdir -p "$SESSION_DIR"

TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
GIT_STATUS=$(git status --short 2>/dev/null | head -20 || echo "not a git repo")
GIT_BRANCH=$(git branch --show-current 2>/dev/null || echo "unknown")

cat > "$CHECKPOINT_FILE" <<EOF
# Context Checkpoint
**Compacted:** $TIMESTAMP
**Trigger:** $TRIGGER
**Branch:** $GIT_BRANCH

## Summary (generated by Claude Code)

$SUMMARY

## Working Tree at Compaction

\`\`\`
$GIT_STATUS
\`\`\`
EOF

echo "[post-compact] Checkpoint saved to $CHECKPOINT_FILE" >&2
exit 0
